# Generated by Django 4.2.7 on 2023-11-26 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_last_login_alter_user_email_alter_user_password"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["name", "email", "password"]},
        ),
    ]
