# Generated by Django 4.2.7 on 2023-11-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_login",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=64),
        ),
    ]
